name: WB Storage Sync

on:
  schedule:
    - cron: '0 6 * * *'  # Каждый день в 06:00 UTC (09:00 МСК)
  workflow_dispatch:     # Можно запустить вручную

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      WB_API_KEY: ${{ secrets.WB_API_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv supabase

    - name: Run initial load (только при первом запуске)
      if: github.event_name == 'workflow_dispatch'
      run: python initial_load.py

    - name: Run daily update
      run: python daily_update.py
