name: WB Storage Sync
on:
  schedule:
    - cron: '0 6 * * *'  # Каждый день в 06:00 UTC
  workflow_dispatch:     # Разрешает ручной запуск

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      WB_API_KEY: ${{ secrets.WB_API_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests supabase

      - name: Run script
        run: python daily_update.py
